POST http://localhost:3333/products
content-type: application/json

{
    "name":"caneta rosa",
    "price":7
}

###
GET http://localhost:3333/products

### Passar ID depois da /

GET http://localhost:3333/products/4c690378-a084-4e5b-a8fd-b6dc5fa083e1

### Passar ID depois da /
PUT  http://localhost:3333/products/a6780441-430a-4154-b309-089eadb3f570
content-type: application/json

{
    "name":"canetgdfgdgda cor de arco verde",
    "price":7
}

### Passar ID depois da /

DELETE http://localhost:3333/products/a6780441-430a-4154-b309-089eadb3f570
