POST http://localhost:3333/products
content-type: application/json
 
{ 
    "name":"",
    "price":
}

###
GET http://localhost:3333/products

### Passar ID depois da /

GET http://localhost:3333/products/

### Passar ID depois da /
PUT  http://localhost:3333/products/
content-type: application/json

{
    "name":"",
    "price":
}

### Passar ID depois da /

DELETE http://localhost:3333/products/
