POST http://localhost:3333/products
content-type: application/json
 
{ 
    "name":"",
    "price":
}

###
GET http://localhost:3333/products

### Passar ID depois da /

GET http://localhost:3333/products/

### Passar ID depois da /
PUT  http://localhost:3333/products/
content-type: application/json

{
    "name":"",
    "price":
}

### Passar ID depois da /

DELETE http://localhost:3333/products/
  
####
GET http://localhost:3333/user/LIST 
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzAzMDA1NTE0LCJleHAiOjE3MDMwMDU4MTR9.AbM-OXSHvVZwwASoQl2hoFTbpvKB1DFWg3nWrL71Wbo